/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Advertisements: () => import('#controllers/advertisements_controller'),
  Analytics: () => import('#controllers/analytics_controller'),
  ApiTokens: () => import('#controllers/api_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Languages: () => import('#controllers/languages_controller'),
  Posts: () => import('#controllers/posts_controller'),
  ServerCategories: () => import('#controllers/server_categories_controller'),
  Servers: () => import('#controllers/servers_controller'),
  Stats: () => import('#controllers/stats_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
  Users: () => import('#controllers/users_controller'),
  WebsiteStats: () => import('#controllers/website_stats_controller'),
}
