server:
  # Port par défaut pour l’UI & l’API de Promtail
  http_listen_port: 9080
  # On désactive le port gRPC si vous n’en avez pas besoin
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'docker-logs'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        # On peut préciser des filtres par label, mais on va plutôt filtrer
        # dans la section relabel_configs pour capturer le nom de conteneur.
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
        action: replace
