apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-backend-config
  namespace: staging
data:
  APP_NAME: "prod"
  PORT: "3333"
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  DB_HOST: postgres-staging
  DB_PORT: "5432"
  DB_USER: "minecraft_stats"
  DB_DATABASE: "minecraft_stats"
  WEBSITE_URL: "https://staging.minecraft-stats.fr"
  TZ: "UTC"
