apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-staging-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path