apiVersion: v1
kind: Secret
metadata:
  name: staging-backend-secrets
  namespace: staging
type: Opaque
stringData:
  APP_KEY: ""
  DB_PASSWORD: ""
  RESEND_API_KEY: ""
  JWT_SECRET: ""
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
