/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdvertisementCategorySchema extends BaseModel {
  static $columns = ['advertisementId', 'categoryId', 'createdAt', 'id', 'updatedAt'] as const
  $columns = AdvertisementCategorySchema.$columns
  @column()
  declare advertisementId: number | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdvertisementEventSchema extends BaseModel {
  static $columns = [
    'advertisementId',
    'createdAt',
    'id',
    'placement',
    'serverId',
    'targetUrl',
    'type',
  ] as const
  $columns = AdvertisementEventSchema.$columns
  @column()
  declare advertisementId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare placement: string | null
  @column()
  declare serverId: number | null
  @column()
  declare targetUrl: string | null
  @column()
  declare type: string
}

export class AdvertisementSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'enabled',
    'endsAt',
    'htmlContent',
    'id',
    'name',
    'showOnHome',
    'showOnServer',
    'startsAt',
    'type',
    'updatedAt',
    'weight',
  ] as const
  $columns = AdvertisementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare enabled: boolean
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare htmlContent: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare showOnHome: boolean
  @column()
  declare showOnServer: boolean
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LanguageSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'flag', 'id', 'name', 'updatedAt'] as const
  $columns = LanguageSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare flag: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PageViewDailySchema extends BaseModel {
  static $columns = ['date', 'id', 'path', 'uniqueVisitors', 'views'] as const
  $columns = PageViewDailySchema.$columns
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string
  @column()
  declare uniqueVisitors: number
  @column()
  declare views: number
}

export class PageViewSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'durationMs',
    'id',
    'path',
    'referrer',
    'title',
    'userId',
    'visitorId',
  ] as const
  $columns = PageViewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare durationMs: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string
  @column()
  declare referrer: string | null
  @column()
  declare title: string | null
  @column()
  declare userId: number | null
  @column()
  declare visitorId: number
}

export class PostSchema extends BaseModel {
  static $columns = [
    'content',
    'coverImage',
    'createdAt',
    'excerpt',
    'id',
    'published',
    'publishedAt',
    'slug',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = PostSchema.$columns
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare excerpt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare published: boolean | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ServerCategorySchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'id', 'serverId', 'updatedAt'] as const
  $columns = ServerCategorySchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare serverId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ServerGrowthStatSchema extends BaseModel {
  static $columns = [
    'lastMonthAverage',
    'lastUpdated',
    'lastWeekAverage',
    'monthlyGrowth',
    'previousWeekAverage',
    'serverId',
    'weeklyGrowth',
  ] as const
  $columns = ServerGrowthStatSchema.$columns
  @column()
  declare lastMonthAverage: number | null
  @column.dateTime()
  declare lastUpdated: DateTime | null
  @column()
  declare lastWeekAverage: number | null
  @column()
  declare monthlyGrowth: number | null
  @column()
  declare previousWeekAverage: number | null
  @column({ isPrimary: true })
  declare serverId: number
  @column()
  declare weeklyGrowth: number | null
}

export class ServerLanguageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'languageId', 'serverId', 'updatedAt'] as const
  $columns = ServerLanguageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare languageId: number | null
  @column()
  declare serverId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ServerStatSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'maxCount', 'playerCount', 'serverId'] as const
  $columns = ServerStatSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxCount: number | null
  @column()
  declare playerCount: number | null
  @column()
  declare serverId: number | null
}

export class ServerStatsHourlySchema extends BaseModel {
  static $columns = [
    'avgPlayerCount',
    'hour',
    'maxPlayerCount',
    'samplesCount',
    'serverId',
  ] as const
  $columns = ServerStatsHourlySchema.$columns
  @column()
  declare avgPlayerCount: number | null
  @column.dateTime()
  declare hour: DateTime
  @column()
  declare maxPlayerCount: number | null
  @column()
  declare samplesCount: number
  @column({ isPrimary: true })
  declare serverId: number
}

export class ServerSchema extends BaseModel {
  static $columns = [
    'address',
    'categoryId',
    'createdAt',
    'faviconHash',
    'id',
    'imageUrl',
    'lastMaxCount',
    'lastOnlineAt',
    'lastPlayerCount',
    'lastStatsAt',
    'motd',
    'motdHash',
    'name',
    'nextPingAt',
    'peakPlayerAt',
    'peakPlayerCount',
    'port',
    'resolvedEndpoint',
    'type',
    'updatedAt',
    'userId',
    'version',
    'website',
  ] as const
  $columns = ServerSchema.$columns
  @column()
  declare address: string
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare faviconHash: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare lastMaxCount: number | null
  @column.dateTime()
  declare lastOnlineAt: DateTime | null
  @column()
  declare lastPlayerCount: number | null
  @column.dateTime()
  declare lastStatsAt: DateTime | null
  @column()
  declare motd: string | null
  @column()
  declare motdHash: string | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextPingAt: DateTime | null
  @column.dateTime()
  declare peakPlayerAt: DateTime | null
  @column()
  declare peakPlayerCount: number | null
  @column()
  declare port: number
  @column()
  declare resolvedEndpoint: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare version: string | null
  @column()
  declare website: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'createdAt',
    'email',
    'id',
    'password',
    'provider',
    'role',
    'updatedAt',
    'username',
    'verificationToken',
    'verificationTokenExpires',
    'verified',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare provider: string | null
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare verificationToken: string | null
  @column.dateTime()
  declare verificationTokenExpires: DateTime | null
  @column()
  declare verified: boolean | null
}

export class VisitorAccountSchema extends BaseModel {
  static $columns = ['id', 'lastActiveAt', 'linkedAt', 'userId', 'visitorId'] as const
  $columns = VisitorAccountSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastActiveAt: DateTime | null
  @column.dateTime()
  declare linkedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare visitorId: number
}

export class VisitorSchema extends BaseModel {
  static $columns = [
    'country',
    'firstSeenAt',
    'id',
    'ipHash',
    'lastSeenAt',
    'userAgent',
    'uuid',
  ] as const
  $columns = VisitorSchema.$columns
  @column()
  declare country: string | null
  @column.dateTime()
  declare firstSeenAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipHash: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare uuid: string
}
