/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdvertisementCategorySchema extends BaseModel {
  static $columns = ['advertisementId', 'categoryId', 'createdAt', 'id', 'updatedAt'] as const
  $columns = AdvertisementCategorySchema.$columns
  @column()
  declare advertisementId: number | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdvertisementEventSchema extends BaseModel {
  static $columns = [
    'advertisementId',
    'createdAt',
    'id',
    'placement',
    'serverId',
    'targetUrl',
    'type',
  ] as const
  $columns = AdvertisementEventSchema.$columns
  @column()
  declare advertisementId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare placement: string | null
  @column()
  declare serverId: number | null
  @column()
  declare targetUrl: string | null
  @column()
  declare type: string
}

export class AdvertisementSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'enabled',
    'endsAt',
    'htmlContent',
    'id',
    'name',
    'showOnHome',
    'showOnServer',
    'startsAt',
    'type',
    'updatedAt',
    'weight',
  ] as const
  $columns = AdvertisementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare enabled: boolean
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare htmlContent: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare showOnHome: boolean
  @column()
  declare showOnServer: boolean
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlacklistedIdentifierUserSchema extends BaseModel {
  static $columns = ['blacklistedIdentifierId', 'createdAt', 'id', 'userId'] as const
  $columns = BlacklistedIdentifierUserSchema.$columns
  @column()
  declare blacklistedIdentifierId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
}

export class BlacklistedIdentifierSchema extends BaseModel {
  static $columns = ['blacklistedBy', 'createdAt', 'id', 'reason', 'type', 'value'] as const
  $columns = BlacklistedIdentifierSchema.$columns
  @column()
  declare blacklistedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string | null
  @column()
  declare type: string
  @column()
  declare value: string
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LanguageSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'flag', 'id', 'name', 'updatedAt'] as const
  $columns = LanguageSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare flag: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MinecraftPlayerSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'headPath',
    'id',
    'resolvedAt',
    'textureHash',
    'updatedAt',
    'username',
    'uuid',
  ] as const
  $columns = MinecraftPlayerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare headPath: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare textureHash: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare uuid: string
}

export class PageViewDailySchema extends BaseModel {
  static $columns = ['date', 'id', 'path', 'uniqueVisitors', 'views'] as const
  $columns = PageViewDailySchema.$columns
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string
  @column()
  declare uniqueVisitors: number
  @column()
  declare views: number
}

export class PageViewSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'durationMs',
    'id',
    'path',
    'referrer',
    'title',
    'userId',
    'visitorId',
  ] as const
  $columns = PageViewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare durationMs: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string
  @column()
  declare referrer: string | null
  @column()
  declare title: string | null
  @column()
  declare userId: number | null
  @column()
  declare visitorId: number
}

export class PostFeedbackSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'helpful',
    'id',
    'postId',
    'updatedAt',
    'userId',
    'visitorId',
  ] as const
  $columns = PostFeedbackSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare helpful: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare visitorId: string
}

export class PostTranslationSchema extends BaseModel {
  static $columns = [
    'content',
    'createdAt',
    'excerpt',
    'id',
    'locale',
    'postId',
    'slug',
    'title',
    'updatedAt',
  ] as const
  $columns = PostTranslationSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare excerpt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare postId: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostSchema extends BaseModel {
  static $columns = [
    'coverImage',
    'createdAt',
    'defaultLocale',
    'id',
    'published',
    'publishedAt',
    'updatedAt',
    'userId',
    'viewCount',
  ] as const
  $columns = PostSchema.$columns
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare defaultLocale: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare published: boolean | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewCount: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ServerBoostReviewSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'note',
    'reviewedBy',
    'scoreAtReview',
    'serverId',
    'signalsAtReview',
    'updatedAt',
    'verdict',
  ] as const
  $columns = ServerBoostReviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare scoreAtReview: number
  @column()
  declare serverId: number
  @column()
  declare signalsAtReview: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare verdict: string
}

export class ServerBoostScoreSchema extends BaseModel {
  static $columns = [
    'computedAt',
    'detectedFactor',
    'estimatedRealPlayers',
    'level',
    'samplesCount',
    'score',
    'serverId',
    'signals',
    'windowFrom',
    'windowTo',
  ] as const
  $columns = ServerBoostScoreSchema.$columns
  @column.dateTime()
  declare computedAt: DateTime
  @column()
  declare detectedFactor: string | null
  @column()
  declare estimatedRealPlayers: number | null
  @column()
  declare level: string
  @column()
  declare samplesCount: number
  @column()
  declare score: number
  @column({ isPrimary: true })
  declare serverId: number
  @column()
  declare signals: any
  @column.dateTime()
  declare windowFrom: DateTime
  @column.dateTime()
  declare windowTo: DateTime
}

export class ServerCategorySchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'id', 'serverId', 'updatedAt'] as const
  $columns = ServerCategorySchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare serverId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ServerGrowthStatSchema extends BaseModel {
  static $columns = [
    'lastMonthAverage',
    'lastUpdated',
    'lastWeekAverage',
    'monthlyGrowth',
    'previousWeekAverage',
    'serverId',
    'weeklyGrowth',
  ] as const
  $columns = ServerGrowthStatSchema.$columns
  @column()
  declare lastMonthAverage: number | null
  @column.dateTime()
  declare lastUpdated: DateTime | null
  @column()
  declare lastWeekAverage: number | null
  @column()
  declare monthlyGrowth: number | null
  @column()
  declare previousWeekAverage: number | null
  @column({ isPrimary: true })
  declare serverId: number
  @column()
  declare weeklyGrowth: number | null
}

export class ServerLanguageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'languageId', 'serverId', 'updatedAt'] as const
  $columns = ServerLanguageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare languageId: number | null
  @column()
  declare serverId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ServerOwnershipClaimSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'evidence',
    'evidenceUrl',
    'expiresAt',
    'id',
    'method',
    'reviewNote',
    'reviewedBy',
    'serverId',
    'status',
    'token',
    'updatedAt',
    'userId',
    'verifiedAt',
  ] as const
  $columns = ServerOwnershipClaimSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare evidence: string | null
  @column()
  declare evidenceUrl: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare method: string
  @column()
  declare reviewNote: string | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare serverId: number
  @column()
  declare status: string
  @column()
  declare token: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class ServerStatSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'maxCount', 'playerCount', 'serverId'] as const
  $columns = ServerStatSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxCount: number | null
  @column()
  declare playerCount: number | null
  @column()
  declare serverId: number | null
}

export class ServerStatsDailySchema extends BaseModel {
  static $columns = [
    'avgPlayerCount',
    'day',
    'maxSlotCount',
    'minPlayerCount',
    'peakPlayerCount',
    'samplesCount',
    'serverId',
  ] as const
  $columns = ServerStatsDailySchema.$columns
  @column()
  declare avgPlayerCount: number | null
  @column.dateTime()
  declare day: DateTime
  @column()
  declare maxSlotCount: number | null
  @column()
  declare minPlayerCount: number | null
  @column()
  declare peakPlayerCount: number | null
  @column()
  declare samplesCount: number
  @column({ isPrimary: true })
  declare serverId: number
}

export class ServerStatsHourlySchema extends BaseModel {
  static $columns = [
    'avgPlayerCount',
    'hour',
    'maxSlotCount',
    'minPlayerCount',
    'peakPlayerCount',
    'samplesCount',
    'serverId',
  ] as const
  $columns = ServerStatsHourlySchema.$columns
  @column()
  declare avgPlayerCount: number | null
  @column.dateTime()
  declare hour: DateTime
  @column()
  declare maxSlotCount: number | null
  @column()
  declare minPlayerCount: number | null
  @column()
  declare peakPlayerCount: number | null
  @column()
  declare samplesCount: number
  @column({ isPrimary: true })
  declare serverId: number
}

export class ServerVoteSchema extends BaseModel {
  static $columns = [
    'country',
    'createdAt',
    'id',
    'ipHash',
    'mojangUuid',
    'serverId',
    'updatedAt',
    'userId',
    'username',
    'visitorId',
  ] as const
  $columns = ServerVoteSchema.$columns
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipHash: string | null
  @column()
  declare mojangUuid: string | null
  @column()
  declare serverId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare username: string
  @column()
  declare visitorId: number | null
}

export class ServerSchema extends BaseModel {
  static $columns = [
    'address',
    'boostReviewedAt',
    'boostStatus',
    'categoryId',
    'createdAt',
    'faviconHash',
    'hostDomain',
    'id',
    'imageUrl',
    'lastMaxCount',
    'lastOnlineAt',
    'lastPlayerCount',
    'lastStatsAt',
    'motd',
    'motdHash',
    'name',
    'nextPingAt',
    'ownerVerifiedAt',
    'ownerVerifiedMethod',
    'peakPlayerAt',
    'peakPlayerCount',
    'port',
    'resolvedEndpoint',
    'type',
    'updatedAt',
    'userId',
    'version',
    'voteCount',
    'website',
  ] as const
  $columns = ServerSchema.$columns
  @column()
  declare address: string
  @column.dateTime()
  declare boostReviewedAt: DateTime | null
  @column()
  declare boostStatus: string | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare faviconHash: string | null
  @column()
  declare hostDomain: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare lastMaxCount: number | null
  @column.dateTime()
  declare lastOnlineAt: DateTime | null
  @column()
  declare lastPlayerCount: number | null
  @column.dateTime()
  declare lastStatsAt: DateTime | null
  @column()
  declare motd: string | null
  @column()
  declare motdHash: string | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextPingAt: DateTime | null
  @column.dateTime()
  declare ownerVerifiedAt: DateTime | null
  @column()
  declare ownerVerifiedMethod: string | null
  @column.dateTime()
  declare peakPlayerAt: DateTime | null
  @column()
  declare peakPlayerCount: number | null
  @column()
  declare port: number
  @column()
  declare resolvedEndpoint: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare version: string | null
  @column()
  declare voteCount: number
  @column()
  declare website: string | null
}

export class TrafficDailySchema extends BaseModel {
  static $columns = [
    'countries',
    'createdAt',
    'date',
    'httpErrors',
    'httpRequests',
    'id',
    'uniqueVisitors',
    'updatedAt',
  ] as const
  $columns = TrafficDailySchema.$columns
  @column()
  declare countries: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare httpErrors: bigint | number
  @column()
  declare httpRequests: bigint | number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare uniqueVisitors: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserProviderSchema extends BaseModel {
  static $columns = [
    'confirmedAt',
    'createdAt',
    'id',
    'linkTokenExpiresAt',
    'linkTokenHash',
    'provider',
    'providerUserId',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserProviderSchema.$columns
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare linkTokenExpiresAt: DateTime | null
  @column()
  declare linkTokenHash: string | null
  @column()
  declare provider: string
  @column()
  declare providerUserId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'blacklistReason',
    'blacklistedAt',
    'blacklistedBy',
    'createdAt',
    'email',
    'id',
    'password',
    'passwordResetToken',
    'passwordResetTokenExpires',
    'provider',
    'role',
    'updatedAt',
    'username',
    'verificationToken',
    'verificationTokenExpires',
    'verified',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare blacklistReason: string | null
  @column.dateTime()
  declare blacklistedAt: DateTime | null
  @column()
  declare blacklistedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare passwordResetToken: string | null
  @column.dateTime()
  declare passwordResetTokenExpires: DateTime | null
  @column()
  declare provider: string | null
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare verificationToken: string | null
  @column.dateTime()
  declare verificationTokenExpires: DateTime | null
  @column()
  declare verified: boolean | null
}

export class VisitorAccountSchema extends BaseModel {
  static $columns = ['id', 'lastActiveAt', 'linkedAt', 'userId', 'visitorId'] as const
  $columns = VisitorAccountSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastActiveAt: DateTime | null
  @column.dateTime()
  declare linkedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare visitorId: number
}

export class VisitorSchema extends BaseModel {
  static $columns = [
    'country',
    'firstSeenAt',
    'id',
    'ipHash',
    'lastSeenAt',
    'userAgent',
    'uuid',
  ] as const
  $columns = VisitorSchema.$columns
  @column()
  declare country: string | null
  @column.dateTime()
  declare firstSeenAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipHash: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare uuid: string
}
