export enum LanguageCode {
  FRENCH = 'fr',
  ENGLISH = 'en',
  SPANISH = 'es',
  GERMAN = 'de',
  ITALIAN = 'it',
  PORTUGUESE = 'pt',
  RUSSIAN = 'ru',
  CHINESE = 'zh',
  JAPANESE = 'ja',
  KOREAN = 'ko',
  DUTCH = 'nl',
  POLISH = 'pl',
  TURKISH = 'tr',
  ARABIC = 'ar',
  OTHER = 'other',
}

export const LANGUAGE_NAMES: Record<LanguageCode, string> = {
  [LanguageCode.FRENCH]: 'Français',
  [LanguageCode.ENGLISH]: 'English',
  [LanguageCode.SPANISH]: 'Español',
  [LanguageCode.GERMAN]: 'Deutsch',
  [LanguageCode.ITALIAN]: 'Italiano',
  [LanguageCode.PORTUGUESE]: 'Português',
  [LanguageCode.RUSSIAN]: 'Русский',
  [LanguageCode.CHINESE]: '中文',
  [LanguageCode.JAPANESE]: '日本語',
  [LanguageCode.KOREAN]: '한국어',
  [LanguageCode.DUTCH]: 'Nederlands',
  [LanguageCode.POLISH]: 'Polski',
  [LanguageCode.TURKISH]: 'Türkçe',
  [LanguageCode.ARABIC]: 'العربية',
  [LanguageCode.OTHER]: 'Autre',
}

export const LANGUAGE_FLAGS: Record<LanguageCode, string> = {
  [LanguageCode.FRENCH]: '🇫🇷',
  [LanguageCode.ENGLISH]: '🇬🇧',
  [LanguageCode.SPANISH]: '🇪🇸',
  [LanguageCode.GERMAN]: '🇩🇪',
  [LanguageCode.ITALIAN]: '🇮🇹',
  [LanguageCode.PORTUGUESE]: '🇵🇹',
  [LanguageCode.RUSSIAN]: '🇷🇺',
  [LanguageCode.CHINESE]: '🇨🇳',
  [LanguageCode.JAPANESE]: '🇯🇵',
  [LanguageCode.KOREAN]: '🇰🇷',
  [LanguageCode.DUTCH]: '🇳🇱',
  [LanguageCode.POLISH]: '🇵🇱',
  [LanguageCode.TURKISH]: '🇹🇷',
  [LanguageCode.ARABIC]: '🇸🇦',
  [LanguageCode.OTHER]: '🌐',
}
